/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.misc.repository.mapper.author;

import com.smart.classroom.misc.repository.orm.author.AuthorDO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AuthorMapper extends AuthorBaseMapper {

    AuthorDO queryTopByUsername(String username);
}