/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.misc.repository.mapper.payment;

import com.smart.classroom.misc.domain.biz.payment.enums.PayStatus;
import com.smart.classroom.misc.repository.orm.column.ColumnDO;
import com.smart.classroom.misc.repository.orm.payment.PaymentDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface PaymentMapper extends PaymentBaseMapper {

    PaymentDO queryByOrderNo(@Param("orderNo") String orderNo);

    int updateStatus(@Param("paymentId") long paymentId, @Param("status") PayStatus status);
}