/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.misc.repository.mapper.article;

import com.github.pagehelper.Page;
import com.smart.classroom.misc.domain.biz.article.enums.ArticleStatus;
import com.smart.classroom.misc.repository.mapper.base.BaseMapper;
import com.smart.classroom.misc.repository.orm.article.ArticleDO;
import com.smart.classroom.misc.utility.enums.SortDirection;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ArticleBaseMapper extends BaseMapper<ArticleDO> {

    /**
     * 当入参中含有PageNum和pageSize时，会自动分页。
     */
    Page<ArticleDO> page(
            @Param("pageNum") int pageNum,
            @Param("pageSize") int pageSize,
            @Param("orderCreateTime") SortDirection orderCreateTime,
            @Param("orderUpdateTime") SortDirection orderUpdateTime,
            @Param("name") String name,
            @Param("content") String content,
            @Param("columnId") Long columnId,
            @Param("authorId") Long authorId,
            @Param("status") ArticleStatus status
    );

}