/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.misc.repository.mapper.reader;

import com.smart.classroom.misc.repository.orm.reader.ReaderDO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ReaderMapper extends ReaderBaseMapper {

    ReaderDO queryByUsername(String username);
}