/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.misc.repository.orm.contract;

import com.smart.classroom.misc.domain.biz.contract.enums.ContractStatus;
import com.smart.classroom.misc.repository.orm.base.BaseEntityDO;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * 作者表
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class ContractDO extends BaseEntityDO {

    /**
     * 名称
     */
    private String name = null;

    /**
     * 内容
     */
    private String content = null;

    /**
     * 专栏id
     */
    private Long columnId = null;

    /**
     * 作者id
     */
    private Long authorId = null;

    /**
     * 状态 NEW/OK/DISABLED 未生效/已生效/已禁用
     */
    private ContractStatus status = ContractStatus.NEW;

    /**
     * 分成比例
     */
    private BigDecimal percentage = null;

    /**
     * 账期日
     */
    private String paymentDay = null;


}