/**
 * smart-classroom.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
package com.smart.classroom.misc.repository.mapper.column;

import com.smart.classroom.misc.repository.orm.column.ColumnDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ColumnMapper extends ColumnBaseMapper {

    ColumnDO queryTopByName(@Param("name") String name);
}